title: "Better StimulusJS"
theme: just-the-docs
url: "http://localhost:4000"
aux_links:
  "GitHub":
    - "//github.com/julianrubisch/better-stimulus"
repository: "julianrubisch/better-stimulus"
plugins:
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-avatar
  # - jekyll-feed
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-titles-from-headings
  - jekyll-turbolinks
  - jekyll-last-modified-at
sass:
  style: compressed
relative_links:
  enabled:     true
  collections: true
turbolinks:
  url: /turbolinks.js
